name: Release CI

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: '发布类型'
        required: true
        default: 'beta'
        type: choice
        options:
          - stable
          - beta
          - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure release type
        id: release_type
        run: echo "RELEASE_TYPE=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV

      - name: Set up Gradle
        uses run: ./gradlew assemble${{ env.RELEASE_TYPE }}

      - name: Sign APK
        if: env.RELEASE_TYPE == 'stable'
        run: |
          echo "${{ secrets.SIGNING_PROPERTIES }}" > signing.properties
          echo "${{ secrets.SIGN_KEY }}" | base64 -d > key.jks
          ./gradlew assembleRelease -PsigningProperties=signing.properties -PsigningKey=key.jks
        env:
          SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mytv-apk
          path: app/build/outputs/apk/

      # 可选：推送到 Gitee 或其他操作
      - name: Push to Gitee
        if: ${{ env.RELEASE_TYPE == 'stable' && secrets.GITEE_TOKEN != '' }}
        run: |
          # 推送脚本示例
          echo "Push to Gitee"
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}

      # 可选：上传到 Sentry
      - name: Upload to Sentry
        if: ${{ env.RELEASE_TYPE == 'stable' && secrets.SENTRY_AUTH_TOKEN != '' }}
        run: |
          echo "Upload to Sentry"
        env:
          SENTRY_AUTH_TOKEN: $_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}